apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3          ## レプリカ数の指定
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate ## デフォルトがこれなので本当はいらない
  template:            ## PodTemplateのフィールド
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.15
        ports:
        - containerPort: 80
