---
apiVersion: v1       ## Kubernetes APIのバージョン
kind: Pod            ## 対象オブジェクト
metadata:            ## <メタデータの内容>
  name: centos          ## メタデータ名
  labels:               ## ラベル
    name: centos         ## (任意の)ラベル名
spec:                     ## <Podオブジェクトの内容>
  restartPolicy: OnFailure
  containers:
    - name: centos
      image: centos:latest
      command:
        - "/sbin/init"
