apiVersion: v1       ## Kubernetes APIのバージョン
kind: Pod            ## 対象オブジェクト
metadata:            ## <メタデータの内容>
  name: sidecar-pod
  labels:               ## ラベル
    name: nginx         ## (任意の)ラベル名
    role: web           ## (任意の)ロール名
spec:                     ## <Podオブジェクトの内容>
  volumes:
    - name: shared-logs ## 共有するボリュームの指定
      emptyDir: {}

  containers:             ## Podオブジェクトのコンテナ
    - name: app-container  ## コンテナの名前
      image: alpine
      command: ["/bin/sh"]
      args: ["-c", "while true; do date >> /var/logs/app.txt; sleep 5; done"]
      volumeMounts: ## アプリケーションのログ出力先
        - name: shared-logs
          mountPath: /var/log

    - name: sidecar-container ## Podの補助コンテナ(ログを参照)
      image: nginx:1.15
      ports:
        - containerPort: 80 ## Podの開放ポート
      volumeMounts:
        - name: shared-logs
          mountPath: /usr/share/nginx/html
