apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    key: rs_sample
spec:
  replicas: 2  ## レプリカ数
  selector:
    matchLabels:
      key: rs_sample
  template:    ## PodTemplateのフィールド
    metadata:
      labels:
        key: rs_sample 
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.15
