---
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: nginx
spec:
  replicas: 2  ## レプリカ数
  template:    ## PodTemplateのフィールド
    metadata:
      labels:
        app: nginx   ## ReplicaSetのmetadataと同じラベル
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.15
