apiVersion: skaffold/v1beta8
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:buildkit"
  artifacts:
     - image: skaffold/payment
       context: .
  local:
    useBuildkit: true
    push: false
deploy:
  kubectl:
    manifests:
      - k8s/app/*.yaml
